[package]
name = "bindgen-example"
version = "0.1.0"
edition = "2024"

[build-dependencies]
bindgen = "=0.72.0" # Pin version to ensure reproducible builds
cc = "=1.2.29"      # Pin version to ensure reproducible builds