
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/*
Note (ingo): On my machine, the bindings.rs file is located in ./target/debug/build/bindgen-example-XXX/out/bindings.rs and looks like this:

// automatically generated by rust-bindgen 0.72.0
pub const CONST_DEFINE_INT: u32 = 42;
pub const CONST_DEFINE_FLOAT: f64 = 3.14;
pub const MyEnum_ENUM_VALUE_ONE: MyEnum = 1;
pub const MyEnum_ENUM_VALUE_TWO: MyEnum = 2;
pub const MyEnum_ENUM_VALUE_THREE: MyEnum = 3;
pub type MyEnum = ::std::os::raw::c_uint;
pub const GLOBAL_VARIABLE: ::std::os::raw::c_int = 4;
*/

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_constants_and_enum() {
        // #define integer constant
        assert_eq!(CONST_DEFINE_INT, 42);

        // #define float constant
        assert!((CONST_DEFINE_FLOAT - 3.14).abs() < 1e-6);

        // Enum values (cast enum to integer)
        assert_eq!(MyEnum_ENUM_VALUE_ONE as i32, 1);
        assert_eq!(MyEnum_ENUM_VALUE_TWO as i32, 2);
        assert_eq!(MyEnum_ENUM_VALUE_THREE as i32, 3);
        
        // Enum values (cast enum to integer)
        assert_eq!(MyEnum_ENUM_VALUE_ONE as i32, 1);
        assert_eq!(MyEnum_ENUM_VALUE_TWO as i32, 2);
        assert_eq!(MyEnum_ENUM_VALUE_THREE as i32, 3);

        // const global variable
        assert_eq!(GLOBAL_VARIABLE, 4);

    }
}